In [1]:
#nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 10, (3,3))
#biến A thành floating point
A = A.astype(float)
print(A)

[[1. 6. 6.]
 [9. 1. 1.]
 [1. 7. 2.]]


In [2]:
#rank của ma trận A
print(np.linalg.matrix_rank(A))

3


In [3]:
from qr_by_given_rotations import QRByGivenRotation


qr_by_given_rotation = QRByGivenRotation(A)
qr_by_given_rotation.decomposite()
R = qr_by_given_rotation.R
print(R)

Ma trận R:
[[1. 6. 6.]
 [9. 1. 1.]
 [1. 7. 2.]]
Ma trận R:
[[ 9.05538514e+00  1.65647289e+00  1.65647289e+00]
 [-1.11022302e-16 -5.85287088e+00 -5.85287088e+00]
 [ 1.00000000e+00  7.00000000e+00  2.00000000e+00]]
Ma trận R:
[[ 9.11043358e+00  2.41481372e+00  1.86599242e+00]
 [-1.11022302e-16 -5.85287088e+00 -5.85287088e+00]
 [-1.11022302e-16  6.77588202e+00  1.80609378e+00]]
[[ 9.11043358e+00  2.41481372e+00  1.86599242e+00]
 [-1.11022302e-16  8.95369615e+00  5.19271317e+00]
 [-1.11022302e-16  0.00000000e+00  3.24866161e+00]]


In [4]:
print(qr_by_given_rotation.rotations)

[GivenRotation(0.11043152607484653, 0.9938837346736189, 0, 1)
, GivenRotation(0.9939576486092934, 0.10976425998969036, 0, 2)
, GivenRotation(-0.653682097946686, 0.7567692612837941, 1, 2)
]


In [5]:
#mình sẽ test bằng cách lấy cột đầu tiên của R, tác động lên nó rotation rồi xem nó có bằng cột 1 của A ko
R0 = R[:, 2].copy()
test_column2 = qr_by_given_rotation.left_multiply_Q(R0)
print(test_column2, A[:, 2])
print(R0, A[:, 2])

[6. 1. 2.] [6. 1. 2.]
[1.86599242 5.19271317 3.24866161] [6. 1. 2.]


In [6]:
#so sánh chuẩn của A[0] và R[0]
print(np.linalg.norm(A[:, 0]), np.linalg.norm(R[:, 0]))

9.1104335791443 9.110433579144297
