In [1]:
#nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 10, (3,3))
#biến A thành floating point
A = A.astype(float)
print(A)

[[2. 4. 8.]
 [3. 8. 8.]
 [8. 3. 5.]]


In [2]:
#rank của ma trận A
print(np.linalg.matrix_rank(A))

3


In [3]:
from qr_by_householder_vectors import QRByHouseholderVector


qr = QRByHouseholderVector(A)
R, householder_vectors = qr.decomposite()
print(R)


[[-8.77496439e+00 -6.38179228e+00 -9.11684612e+00]
 [-4.44089210e-16 -6.94785775e+00 -7.60208164e+00]
 [-1.77635684e-15 -8.88178420e-16  3.47727934e+00]]


In [5]:
#print the householder vectors
for i in range(len(householder_vectors)):
    print(householder_vectors[i])

HouseholderVector: v = [0.78355636 0.21816027 0.58176071], i = 0

HouseholderVector: v = [ 0.93150469 -0.36372932], i = 1

HouseholderVector: v = [-1.], i = 2



In [6]:
R0 = R[:, 2].copy()
test_column2 = qr.left_multiply_Q(R0)
print(test_column2, A[:, 2])
print(R0, A[:, 2])

[8. 8. 5.] [8. 8. 5.]
[-9.11684612 -7.60208164  3.47727934] [8. 8. 5.]


In [7]:
#so sánh chuẩn của A[0] và R[0]
print(np.linalg.norm(A[:, 0]), np.linalg.norm(R[:, 0]))

8.774964387392123 8.774964387392123
