In [153]:
#nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 10, (5,5))
#biến A thành floating point
A = A.astype(np.float64)
for i in range(5):
    for j in range(5):
        if i > j:
            A[i][j] = A[j][i]
print(A)

[[1. 6. 2. 5. 6.]
 [6. 2. 4. 1. 5.]
 [2. 4. 7. 3. 8.]
 [5. 1. 3. 6. 2.]
 [6. 5. 8. 2. 9.]]


In [154]:
#rank của ma trận A
print(np.linalg.matrix_rank(A))

5


In [155]:
#tính QR factorization của ma trận A
from qr_by_given_rotations import QRByGivenRotation


qr = QRByGivenRotation(A)
R, rotations = qr.decomposite()
print('Ma trận R:', R)

Ma trận R: [[ 1.00995049e+01  6.03990001e+00  1.01985197e+01  5.84187050e+00
   1.14857115e+01]
 [-1.11022302e-16 -6.74682206e+00 -4.35789777e+00 -3.66330786e+00
  -8.24498564e+00]
 [ 2.22044605e-16  0.00000000e+00  4.35877541e+00 -1.50105291e+00
   2.96687471e+00]
 [ 0.00000000e+00  0.00000000e+00  5.55111512e-17  5.01991680e+00
  -7.66650955e-01]
 [ 0.00000000e+00  2.22044605e-16  0.00000000e+00  4.44089210e-16
  -8.41750479e-01]]


In [156]:
def checkHessenberg(A_matrix, eps=1e-10):
    #kiem tra duoi duong cheo phu
    for i in range(0, A_matrix.shape[1]):
        for j in range(i+1, A_matrix.shape[0]):
            if abs(A_matrix[j,i]) > eps:
                print('Duoi duong cheo phu khac 0',j,i, A_matrix[j,i])
                return False
           
            
    return True

In [157]:

list_QR_by_given_rotation = [qr]
counter = 0
while True:
    current_qr = list_QR_by_given_rotation[-1]
    current_qr.decomposite()
    next_A = current_qr.R.copy()
    for i in range(next_A.shape[0]):
        next_A[i] = current_qr.right_multiply_Q(next_A[i])
    list_QR_by_given_rotation.append(QRByGivenRotation(next_A))
    print(next_A)
    counter += 1
    # if counter ==30:
    #     break
    if(checkHessenberg(next_A)):
        break
print('Số lần lặp:', counter)
print('Ma trận A cuối cùng:', list_QR_by_given_rotation[-1].A)


[[ 16.32352941 -11.58306093   1.88262045   2.02977061  -0.5000743 ]
 [-11.58306093   0.86751086  -2.87506961   1.64120965   0.17613531]
 [  1.88262045  -2.87506961   4.13282723  -1.06036407  -0.19877292]
 [  2.02977061   1.64120965  -1.06036407   4.21304502   0.31569   ]
 [ -0.5000743    0.17613531  -0.19877292   0.31569     -0.53691253]]
Duoi duong cheo phu khac 0 1 0 -11.583060927140988
[[ 2.24659595e+01  4.00292561e+00  7.78145126e-02  3.78166784e-01
   1.39478533e-02]
 [ 4.00292561e+00 -4.80416041e+00  2.43330888e+00 -1.47087217e+00
  -5.79432508e-03]
 [ 7.78145126e-02  2.43330888e+00  4.57392639e+00 -1.09119565e+00
   1.58409392e-02]
 [ 3.78166784e-01 -1.47087217e+00 -1.09119565e+00  3.32640463e+00
  -3.67332757e-02]
 [ 1.39478533e-02 -5.79432508e-03  1.58409392e-02 -3.67332757e-02
  -5.62130139e-01]]
Duoi duong cheo phu khac 0 1 0 4.002925606523272
[[ 2.30109024e+01 -1.07809483e+00 -2.05278195e-02  5.00438992e-02
  -3.43711626e-04]
 [-1.07809483e+00 -5.37779230e+00 -2.65639181e+0

In [158]:
last_A = list_QR_by_given_rotation[-1].A
Q = np.identity(A.shape[0])
for i in range(len(list_QR_by_given_rotation)):
    for j in range(A.shape[0]):
        Q[j] =list_QR_by_given_rotation[i].right_multiply_Q(Q[j])
print('Ma trận Q:', Q)

Ma trận Q: [[ 0.38004284 -0.74735328 -0.2936673  -0.45770754 -0.03596995]
 [ 0.364851    0.50108601  0.04235997 -0.49466006 -0.60771179]
 [ 0.5020408  -0.23986082  0.27774481  0.66304834 -0.41670918]
 [ 0.29384211  0.29078696 -0.85065339  0.30652425  0.10738463]
 [ 0.6197282   0.21973988  0.33348431 -0.11056679  0.66649422]]


In [159]:
A_test = Q @ last_A @ Q.T
print('Ma trận A_test:', A_test, A)

Ma trận A_test: [[1. 6. 2. 5. 6.]
 [6. 2. 4. 1. 5.]
 [2. 4. 7. 3. 8.]
 [5. 1. 3. 6. 2.]
 [6. 5. 8. 2. 9.]] [[1. 6. 2. 5. 6.]
 [6. 2. 4. 1. 5.]
 [2. 4. 7. 3. 8.]
 [5. 1. 3. 6. 2.]
 [6. 5. 8. 2. 9.]]


In [160]:
#dung scipy để tính eigenvalue và eigenvector
from scipy.linalg import eig
eigenvalues, eigenvectors = eig(A)

#tinh Av - lambda*v
for i in range(len(eigenvalues)):
    print(np.linalg.norm( A @ eigenvectors[:,i] - eigenvalues[i] * eigenvectors[:,i]))
    print('\n')


3.907985046680551e-14


7.666168367507028e-15


5.811728571835198e-15


4.976536781825725e-15


1.5865807844426728e-15




In [161]:
#tinh Av - lambda*v cua minh
for i in range(len(eigenvalues)):
    print(np.linalg.norm( A @ Q[:,i] - last_A[i,i] * Q[:,i]))
    print('\n')

3.83976696149398e-14


9.768518602973628e-11


9.768459080592094e-11


1.093217394395933e-14


6.717709437368064e-15




In [162]:
last_A

array([[ 2.30521647e+001, -3.24241414e-015,  5.39007214e-016,
        -1.77540985e-016,  1.60448375e-015],
       [ 2.96439388e-323, -6.09058035e+000, -9.76748121e-011,
         1.49104945e-015,  1.94789902e-015],
       [ 4.94065646e-324, -9.76750287e-011,  5.91274173e+000,
         7.27566536e-016, -9.84734598e-016],
       [-1.48219694e-323,  5.69849468e-290, -1.80084521e-279,
         2.68807172e+000, -2.54985576e-016],
       [ 3.95252517e-323, -4.94065646e-324, -9.88131292e-324,
         4.94065646e-324, -5.62397751e-001]])