In [9]:
#nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 10, (5,5))
#biến A thành floating point
A = A.astype(float)
print(A)

[[6. 3. 4. 6. 2.]
 [8. 2. 8. 4. 3.]
 [3. 1. 2. 3. 8.]
 [7. 5. 8. 2. 8.]
 [4. 8. 9. 1. 1.]]


In [10]:
#rank của ma trận A
print(np.linalg.matrix_rank(A))

5


In [11]:
#tính QR factorization của ma trận A
from qr_by_given_rotations import QRByGivenRotation


qr = QRByGivenRotation(A)
R, rotations = qr.decomposite()
print('Ma trận R:', R)

Ma trận R: [[ 1.31909060e+01  7.88421965e+00  1.41006236e+01  7.20193141e+00
   9.09717652e+00]
 [ 0.00000000e+00  6.39054618e+00  4.82393607e+00 -1.53063743e+00
  -5.82757377e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.62717616e+00  2.72841506e+00
   1.69942077e+00]
 [ 0.00000000e+00  2.22044605e-16  0.00000000e+00  2.08448656e+00
  -2.90045375e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   6.89935578e+00]]


In [12]:
#Tinh A1 = RQ
A1 = R.copy()
for i in range(4):
    A1[i] = qr.right_multiply_Q(A1[i])
print('Ma trận A1:', A1)

Ma trận A1: [[20.56896552  2.51286939  7.09069077  6.16405514  7.20726135]
 [ 3.98385723 -4.08725992 -2.59751706  4.09188811  3.27481931]
 [ 1.36571818  2.1661127  -0.82258967 -2.39924167 -2.06011883]
 [ 0.2266403  -2.27962974  0.61936187 -2.65911593  0.23480187]
 [ 0.          0.          0.          0.          6.89935578]]


In [13]:
def checkHessenberg(A_matrix, eps=0.1):
    #kiem tra duoi duong cheo phu
    for i in range(0, A_matrix.shape[1]):
        for j in range(i+2, A_matrix.shape[0]):
            if abs(A_matrix[j,i]) > eps:
                print('Duoi duong cheo phu khac 0',j,i, A_matrix[j,i])
                return False
            
    return True

In [14]:
qr2 = QRByGivenRotation(A1)
R2, rotations2 = qr2.decomposite()
print('Ma trận R2:', R2)

A2 = R2.copy()
for i in range(4):
    A2[i] = qr2.right_multiply_Q(A2[i])
print('Ma trận A2:', A2)


Ma trận R2: [[ 2.09969048e+01  1.80244220e+00  6.40651490e+00  6.63004314e+00
   7.55025551e+00]
 [ 0.00000000e+00 -5.44611460e+00 -2.51437909e+00  2.26228115e+00
   2.54874205e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.27409806e+00  1.03293839e+00
  -7.56178210e-01]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16 -4.17421040e+00
  -1.70118467e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   6.89935578e+00]]
Ma trận A2: [[21.39922128 -1.02600851 -1.02713595  8.31175931  7.55025551]
 [-1.17244672 -2.52829081 -5.73289621  0.68351869  2.54874205]
 [-0.20181021  1.66780023 -2.69368354 -1.30708219 -0.75617821]
 [-0.04505637 -1.76214905  2.05473479 -3.17724693 -1.70118467]
 [ 0.          0.          0.          0.          6.89935578]]


In [15]:

list_QR_by_given_rotation = [qr]
counter = 0
while True:
    current_qr = list_QR_by_given_rotation[-1]
    current_qr.decomposite()
    next_A = current_qr.R.copy()
    for i in range(next_A.shape[0]):
        next_A[i] = current_qr.right_multiply_Q(next_A[i])
    list_QR_by_given_rotation.append(QRByGivenRotation(next_A))
    print(next_A)
    counter += 1
    if counter ==30:
        break
    if(checkHessenberg(next_A)):
        break
print('Số lần lặp:', counter)
print('Ma trận A cuối cùng:', list_QR_by_given_rotation[-1].A)


[[ 2.05689655e+01  2.51286939e+00  7.09069077e+00  6.16405514e+00
   7.20726135e+00]
 [ 3.98385723e+00 -4.08725992e+00 -2.59751706e+00  4.09188811e+00
   3.27481931e+00]
 [ 1.36571818e+00  2.16611270e+00 -8.22589669e-01 -2.39924167e+00
  -2.06011883e+00]
 [ 2.26640300e-01 -2.27962974e+00  6.19361871e-01 -2.65911593e+00
   2.34801867e-01]
 [ 2.09215525e+00  6.05579455e+00 -1.28683513e+00  2.21255606e+00
   8.24904085e-16]]
Duoi duong cheo phu khac 0 2 0 1.3657181751586651
[[22.24343965  4.18971724  1.64151683  7.08235745 -5.26717215]
 [ 1.29784882 -6.0057174   5.40981283 -0.57161352  1.41148744]
 [-0.22671057 -1.61249183 -1.49134794 -2.20142337 -4.2328336 ]
 [-0.25076818 -0.24215484 -0.35094048 -2.19446677  4.25765934]
 [-0.0947497  -0.69583852 -0.44901466  0.13280337  0.44809246]]
Duoi duong cheo phu khac 0 2 0 -0.22671056801575518
[[ 2.23901654e+01  2.68444659e+00  8.55887836e-01  8.94824286e+00
  -1.73877879e+00]
 [-4.11159579e-01 -5.05214697e+00  5.92364459e+00 -1.76342597e+00
  -1.