In [1]:
#nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 10, (4,4))
#biến A thành floating point
A = A.astype(float)
print(A)

[[5. 3. 4. 6.]
 [8. 9. 3. 6.]
 [2. 8. 2. 9.]
 [1. 4. 1. 7.]]


In [2]:
#rank của ma trận A
print(np.linalg.matrix_rank(A))

4


In [3]:
''' 






2 6 −3 4 −9
−1 7 −4 −3 −7
−6 −6 −165
9262 −8
−7 −8 6 −9 −1

'''
A = np.array([[2, 6, -3, 4, -9],
                [-1, 7, -4, -3, -7],
               [-6, -6, -1, 6, 5],
               [9,2,6,2,-8],
                [-7, -8, 6, -9, -1]], dtype=float)



In [4]:
#tính QR factorization của ma trận A
from qr_by_given_rotations import QRByGivenRotation


qr = QRByGivenRotation(A)
R, rotations = qr.decomposite()
print('Ma trận R:', R)

Ma trận R: [[ 1.30766968e+01  8.79426980e+00  1.22355058e+00  4.28242703e+00
  -8.10602260e+00]
 [ 0.00000000e+00  1.05669683e+01 -8.21051333e+00  5.05270873e-01
  -6.59729909e+00]
 [-4.44089210e-16  0.00000000e+00  5.39355123e+00 -9.10183861e+00
  -8.94569856e+00]
 [ 0.00000000e+00 -4.44089210e-16  0.00000000e+00 -6.67548155e+00
   5.29930776e+00]
 [ 8.88178420e-16  0.00000000e+00 -2.22044605e-16  0.00000000e+00
  -1.63090677e+00]]


In [5]:
#Tinh A1 = RQ
A1 = R.copy()
for i in range(4):
    A1[i] = qr.right_multiply_Q(A1[i])
print('Ma trận A1:', A1)

Ma trận A1: [[ 8.05263158e+00  1.28016648e+01 -6.14966998e-01 -1.02215686e+01
   5.44878994e-01]
 [ 6.83847338e+00  1.10610167e+01  2.19519148e+00  5.31370586e+00
  -4.54839068e+00]
 [-3.95038331e+00  5.27505516e+00 -1.21505047e+01  2.50336903e-01
  -9.11161091e-01]
 [-7.43111885e+00  9.09043978e-01  1.53869396e+00  2.34827674e+00
   2.95209174e+00]
 [ 8.88178420e-16  0.00000000e+00 -2.22044605e-16  0.00000000e+00
  -1.63090677e+00]]


In [31]:
def checkHessenberg(A_matrix, eps=0.1):
    #kiem tra duoi duong cheo phu
    for i in range(0, A_matrix.shape[1]):
        for j in range(i+2, A_matrix.shape[0]):
            if abs(A_matrix[j,i]) > eps:
                print('Duoi duong cheo phu khac 0',j,i, A_matrix[j,i])
                return False
            
    return True

In [29]:
qr2 = QRByGivenRotation(A1)
R2, rotations2 = qr2.decomposite()
print('Ma trận R2:', R2)

A2 = R2.copy()
for i in range(4):
    A2[i] = qr2.right_multiply_Q(A2[i])
print('Ma trận A2:', A2)


Ma trận R2: [[ 1.35069112e+01  1.11893721e+01  3.45190612e+00 -4.76882833e+00
  -3.33564405e+00]
 [ 8.88178420e-16  1.37724084e+01 -6.16537455e+00 -1.10820735e+00
  -5.90568338e-01]
 [ 0.00000000e+00 -2.77555756e-17  1.02602093e+01  2.74371820e+00
   1.28330880e+00]
 [ 0.00000000e+00  8.88178420e-16 -4.44089210e-16  1.03341749e+01
  -4.17224609e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.63090677e+00]]
Ma trận A2: [[15.33183848 10.09242916 -2.31224528  0.16492682 -3.33564405]
 [ 9.38579219  1.00095911  7.52545158  9.1209519  -0.59056834]
 [-4.51033216  7.77533693 -5.54938696  1.09782914  1.2833088 ]
 [-5.68556949  5.30133656  6.64819869 -1.47199037 -4.17224609]
 [ 0.          0.          0.          0.         -1.63090677]]


In [32]:

list_QR_by_given_rotation = [qr]
counter = 0
while True:
    current_qr = list_QR_by_given_rotation[-1]
    current_qr.decomposite()
    next_A = current_qr.R.copy()
    for i in range(next_A.shape[0]):
        next_A[i] = current_qr.right_multiply_Q(next_A[i])
    list_QR_by_given_rotation.append(QRByGivenRotation(next_A))
    print(next_A)
    counter += 1
    if counter ==30:
        break
    if(checkHessenberg(next_A)):
        break
print('Số lần lặp:', counter)
print('Ma trận A cuối cùng:', list_QR_by_given_rotation[-1].A)


[[  8.05263158  12.80166483  -0.614967   -10.22156865   0.54487899]
 [  6.83847338  11.06101669   2.19519148   5.31370586  -4.54839068]
 [ -3.95038331   5.27505516 -12.15050474   0.2503369   -0.91116109]
 [ -7.43111885   0.90904398   1.53869396   2.34827674   2.95209174]
 [  0.87302991   0.50814893  -1.23878925   0.08876343  -0.31142027]]
Duoi duong cheo phu khac 0 2 0 -3.950383314648938
[[ 1.51222907e+01  1.01289688e+01 -1.58635257e+00 -2.00777055e-01
  -4.46155827e+00]
 [ 9.32556296e+00  1.03155705e+00  7.59693190e+00  9.09717478e+00
  -7.31044871e-01]
 [-4.40410629e+00  7.77758571e+00 -5.87880109e+00  1.18637076e+00
   7.33948924e-01]
 [-5.95800982e+00  5.37484627e+00  7.14553936e+00 -1.67311577e+00
  -2.53362497e+00]
 [ 2.61015048e-02 -6.29266574e-03 -6.04945747e-02  3.02630267e-02
   3.98069137e-01]]
Duoi duong cheo phu khac 0 2 0 -4.404106291969147
[[ 1.57967674e+01  1.21412657e+01  2.35120607e+00 -4.00623126e+00
  -3.21570113e+00]
 [ 7.04405225e+00 -3.25581643e+00  7.10121282e+0