In [1]:
##nhập ma trận A cỡ 5x5 bất kì
import numpy as np
A = np.random.randint(1, 100, (5, 5))
#biến A thành floating point
A = A.astype(float)
print(A)

[[34. 55. 35. 36. 82.]
 [43. 41. 98. 46. 36.]
 [34. 52. 64.  4. 61.]
 [33. 51. 20. 80. 27.]
 [21. 39. 32. 79.  1.]]


In [2]:
n = A.shape[0]

In [3]:
from collections import deque


init_vectors = deque()
id = np.identity(n)
for i in range(n):
    #lay vector don vi
    init_vectors.append(id[i])
print(init_vectors)


deque([array([1., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0.]), array([0., 0., 1., 0., 0.]), array([0., 0., 0., 1., 0.]), array([0., 0., 0., 0., 1.])])


In [4]:
from find_eig_by_power_iteration import find_eig_by_power_iteration


old_eigen_vectors = []
current_eigen_vector = np.zeros(n)
eigen_values = []
eigen_vectors = []
for i in range(n):

    choose_index = 0
    #ma tran A se tru di
    if i > 0:
        A = A - eigen_values[i-1] * np.outer(current_eigen_vector, current_eigen_vector)
    for j in range(len(init_vectors)):
            x0= init_vectors[j] - (init_vectors[j].dot(current_eigen_vector) )* current_eigen_vector
            init_vectors[j] = x0
            #neu chuan no lon hon chuan cua init_vectors[choose_index] thi chon no
            if np.linalg.norm(x0) > np.linalg.norm(init_vectors[choose_index]):
                choose_index = j
    x1 = init_vectors[choose_index]/np.linalg.norm(init_vectors[choose_index])
    #lay random vector
    print('x1 and norm', x1, np.linalg.norm(x1))
    eigen_value, eigen_vector = find_eig_by_power_iteration(matrixA=A, x0=x1, tol=1e-20, maxiter=1000, eigenvectors=eigen_vectors)
    eigen_values.append(eigen_value)
    eigen_vectors.append(eigen_vector.copy())
    current_eigen_vector = eigen_vector.copy()
        
        

x1 and norm [1. 0. 0. 0. 0.] 1.0
x1 and norm [-0.18103113 -0.20129316 -0.16295737 -0.16444327  0.93440468] 1.0
x1 and norm [-2.61454258e-01 -2.90717691e-01  8.89224359e-01 -2.37497230e-01
 -3.12132426e-17] 1.0
x1 and norm [-0.13144846 -0.60678034  0.74779445 -0.12178844  0.20127087] 1.0
x1 and norm [-0.49271065 -0.05849133  0.06017831  0.83932677 -0.21383201] 1.0


In [5]:
print(eigen_values)
print(eigen_vectors)

[220.8729170560726, -38.03177671824525, 38.18216034347182, -7.105372859446219, -0.9610473077673389]
[array([0.47487376, 0.5280243 , 0.42746337, 0.43136112, 0.35621328]), array([-0.18103113, -0.20129316, -0.16295737, -0.16444327,  0.93440468]), array([-0.33447892,  0.60590118,  0.49918985, -0.29876858, -0.4272639 ]), array([-0.13144846, -0.60678034,  0.74779445, -0.12178844,  0.20127087]), array([ 0.45530972, -0.44992055, -0.19529794,  0.48925762,  0.55924078])]


In [6]:
#tinh error
error = []
for i in range(len(eigen_values)):
    error.append(np.linalg.norm(A @ eigen_vectors[i] - eigen_values[i] * eigen_vectors[i]))
print(error)

[221.22103174532637, 58.99530083475023, 38.18216034347181, 58.86968616456875, 6.91375717961828]
